# Generated by Django 4.2.3 on 2023-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('permission_to_contact_over_whatsapp', models.BooleanField(default=False)),
                ('want_to_receive_newsletter', models.BooleanField(default=False)),
                ('pincode', models.CharField(max_length=6)),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
    ]
