# Generated by Django 4.2.1 on 2023-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_donationusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('donationUsage', models.ManyToManyField(to='registration.donationusage')),
                ('volunteers', models.ManyToManyField(to='registration.volunteer')),
            ],
        ),
    ]
