# Generated by Django 4.2.1 on 2023-07-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='donationUsage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='volunteers',
        ),
    ]
